language: node_js
node_js: 11.10.0
branches:
  only:
    - source
notifications:
  email: false
script:
  - git config --global user.name "${GH_NAME}"
  - git config --global user.email "${GH_EMAIL}"
  - echo "machine github.com login ${GH_NAME} password ${GH_TOKEN}" > ~/.netrc
  - npm run deploy
